#########################################################################3
#
# Configure the OSG to use defined Object Storage backend
#

- name: Configure OSG provider
  shell: source "{{ euca_admin_creds_path }}/eucarc" ; euca-modify-property -p "{{ osg_provider_property }}={{ osg_provider_name }}"
  register: osg_result
  until: osg_result.stdout.find("was") != -1
  retries: 20
  delay: 5
  tags:
  - osg_config

- name: Wait for OSG to be ENABLED
  pause: prompt="Making sure OSG is now set to its provider - properties can now be changed" seconds=30
  tags:
  - osg_config
  when:
  - not osg_provider_name == "walrus"

- name: Configure OSG provider properties
  shell: source "{{ euca_admin_creds_path }}/eucarc" ; euca-modify-property -p "{{ item.name }}={{ item.value }}"
  with_items: "{{ osg_properties }}"
  tags:
  - osg_config
  when:
  - not osg_provider_name == "walrus"
